### ISSUE TITLE
tutorial not compatible with latest graph-tool 2.41

### ISSUE THREAD

**Issue by alberto-bracci** [martingerlach/hSBM_Topicmodel#35]
Hi, I believe the multilayer_SBM notebook tutorial is not compatible with the latest graph-tool version. 

In particular, when running the `fit_hyperlink_text_hsb` part, I simply get an error because the `deg_corr` and `layers` arguments in `gt.minimize_nested_blockmodel_dl` are not present any more. 
By looking at graph-tool, it appears they were last present in 2.37 . Maybe you tested the code with earlier versions? 

Just flagging because I saw the recently published paper on EPJDS, it looks great and I was looking forward to apply the methodology to our use case!

**Comment by count0** [comment]
I have already fixed this in my own repository, but forgot to push here... Will do so in a sec.

**Comment by count0** [comment]
The fix is in pull request #37 . Waiting for @martingerlach to merge.

**Comment by alberto-bracci** [comment]
great, thanks for the rapid answer and commit!
From the linked commit it seems you edited the one layer versions of the model: sbmtm.py and TopSBM-tutorial.ipynb/html 
Do these changes also propagate to the multilayer version, namely sbmmultilayer.py and Multilayer_SBM_Tutorial.ipynb ?
From the code they do not seem to share dependencies/code, but I maybe wrong

**Comment by martingerlach** [comment]
@alberto-bracci thanks for bringing up this issue. thanks @count0 for the fix, I just merged. I am closing this issue, but feel free to re-open if something is missing.

**Comment by alberto-bracci** [comment]
I tried it with the multilayer version and I still get the same error. 

A similar fix needs to be implemented in sbmmultilayer.py, and maybe also in the associated notebook Multilayer_SBM_Tutorial.ipynb to make the multilayer version run with the latest graph_tool version

Unfortunately it's my first approach to SBM and graph_tool, so I'm not sure how I can help

**Comment by alberto-bracci** [comment]
I can still run it with an older version of graph_tool I guess, just wondering whether I would have other problems like performance drops or else

**Comment by count0** [comment]
This is fixed in PR #38
